@baseUrl = {{HostAddress}}/api/article


GET {{baseUrl}}/getAll?searchKey="Test"


POST {{baseUrl}}/create
Content-Type: application/json
{
	"title": "Test Article",
	"content": "This is a test article",
	"subHeading": "Test subHeading",
	"userId": 7
}

